apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ft.labels" (dict "name" "web" "component" "frontend" "root" $) | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "ft.selectorLabels" (dict "name" "web") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ft.labels" (dict "name" "web" "component" "frontend" "root" $) | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: {{ include "ft.image" (dict "image" "filament-web" "root" $) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.port }}
          env:
            - name: PORT
              value: {{ .Values.web.port | quote }}
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: CATALOG_URL
              value: "http://catalog-service:{{ .Values.catalog.port }}"
            - name: INVENTORY_URL
              value: "http://inventory-service:{{ .Values.inventory.port }}"
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: next-cache
              mountPath: /app/.next/cache
      volumes:
        - name: tmp
          emptyDir: {}
        - name: next-cache
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ft.labels" (dict "name" "web" "component" "frontend" "root" $) | nindent 4 }}
spec:
  selector:
    {{- include "ft.selectorLabels" (dict "name" "web") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
