apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "garage.labels" (dict "name" "garage" "component" "s3") | nindent 4 }}
  annotations:
    io.cilium/lb-ipam-ips: {{ .Values.loadBalancer.ip | quote }}
spec:
  type: LoadBalancer
  selector:
    {{- include "garage.selectorLabels" (dict "name" "garage") | nindent 4 }}
  ports:
    - name: s3
      port: 3900
      targetPort: s3
      protocol: TCP
    - name: rpc
      port: 3901
      targetPort: rpc
      protocol: TCP
    - name: admin
      port: 3903
      targetPort: admin
      protocol: TCP
